### ISSUE TITLE
add [X] icon per row to close the file

### ISSUE THREAD

**Issue by dericed** [MediaArea/BWFMetaEdit#100]
Currently you can click into a field to select a row and then choose "File>Close file"; however this doesn't work all the time since not all files are editable and then no field can be selected. Users have suggested a "Close file" button per row to remove the file from the table or prompt for that file to be saved if there are unsaved changes for that file.

**Comment by ablwr** [comment]
This is present in File view, although as I note in https://github.com/MediaArea/BWFMetaEdit/issues/106, it could be more apparent.

**Comment by ablwr** [comment]
But agree it would be useful in all views.
