### ISSUE TITLE
UI Feature: Editing in-line instead of pop-up

### ISSUE THREAD

**Issue by ablwr** [MediaArea/BWFMetaEdit#104]
For BWFME users, copying and pasting across fields is difficult. It involves double-clicking, selecting and copying text, saving, going to the next row, double-clicking, and pasting text.

Is it possible to have the editing occur in-line, without creating a new pop-up window? This would save time and simplify the interface substantially.

This is true across views -- File, Tech, and Core.

The pop-up does provide extra information in the context of a learning tool -- it explains what the requirements are. But for advanced and regular users, they already have an understanding of the requirements and just want to add/edit data quickly.

**Comment by JeromeMartinez** [comment]
Inline edition is not fun when you have several lines of content e.g. CodingHistory, and switching between inline and not inline is weird too. This is an UI choice more than a technical issue.

I thin that we could keep "old" UI (Core, Tech) as is, but being inline + a "..." button next to the box with the new "File" UI, it has more space for that.

**Comment by ablwr** [comment]
Okay, I think implementing it with the File UI will be a good step, and it'll be a bit different. I noticed the File UI already has the option of edit mode or display mode.

I'm not saying that the max length should change, just that users should be able to edit without the pop-up box. We had some user feedback related to this, and I think it will save them time when just copying and pasting in some descriptions from another source.

**Comment by JeromeMartinez** [comment]
Implemented slightly differently due to technical limitations with the GUI toolkit, so I close.
