### ISSUE TITLE
UI: In file view, XMP aXML, iXML are not buttons

### ISSUE THREAD

**Issue by ablwr** [MediaArea/BWFMetaEdit#105]
In the file view, the XMP, aXML, iXML text should be buttons that open a pop-up box where users can view, edit, or add metadata.

![Screenshot from 2020-04-19 12-48-58](https://user-images.githubusercontent.com/3260492/79694051-13335000-823c-11ea-88f0-4ada4940c543.png)

**Comment by g-maxime** [comment]
In "Display mode" those buttons are greyed out and disabled if the field is empty.

**Comment by JeromeMartinez** [comment]
Maybe not obvious enough, so we replace by a button, @ablwr  how do we indicate in the view to the user that the field has a content or not?
