### ISSUE TITLE
UI: In file view, some features are too grey/small

### ISSUE THREAD

**Issue by ablwr** [MediaArea/BWFMetaEdit#106]
In file view, there are several useful new features but they are too subtle. The +/- box, edit, save, x, and additional metadata all appear (at least for me, Ubuntu 18.04) as a very light grey and relatively small text (smaller than the data fields such as Version, Description). 

![Screenshot from 2020-04-19 12-52-56](https://user-images.githubusercontent.com/3260492/79694192-d7e55100-823c-11ea-83d9-928ffe93e5e3.png)

Somewhat related, it'd be nice to have a visible scroll-bar on the right, otherwise it's not clear that scrolling is possible. It's more obvious on the Tech/Core views when there are many files, and is always present. 

This can be seen in https://github.com/MediaArea/BWFMetaEdit/issues/105

**Comment by JeromeMartinez** [comment]
> Somewhat related, it'd be nice to have a visible scroll-bar on the right, otherwise it's not clear that scrolling is possible.

This is the "nowadays" classic way to show scrollbars in Qt, actually this is the default when QtQuick API is used. [source](https://doc.qt.io/qt-5/qml-qtquick-controls2-scrollbar.html) (see the first image, just after "Detailed Description").

So before trying to change the default behavior, I would like to be sure that we don't want this default behavior decided by designers from Qt.

**Comment by ablwr** [comment]
If that's the default behavior, should it change in the other views? My problem is that it is inconsistent.

**Comment by JeromeMartinez** [comment]
Other view are with old Qt API, so not the same possibilities.
We'll check what is possible to do.
