### ISSUE TITLE
support view of cues chunk

### ISSUE THREAD

**Issue by dericed** [MediaArea/BWFMetaEdit#107]
Starting a ticket here as this issue has come up several times in discovery interviews. The "cue " chunk contains information that often has a descriptive relationship to the metadata of the bext and LIST-INFO chunk. I'm uncertain if it is in scope of BWF MetaEdit to support editing this chunk but I think it could be useful to view it in BWF MetaEdit.

**Comment by JeromeMartinez** [comment]
A `cue ` chunk editor is not complicated to do, and IMO in the scope of this tool (it is already more than a BWF specific chunk editor), just some development time.

Please provide a sample file.

**Comment by dericed** [comment]
pinging @MarcosSueiro for a sample

**Comment by MarcosSueiro** [comment]
LMK if you cannot download

https://drive.google.com/file/d/1RaykJ719J9XlS1GHSMfcnK-AqIbKc24I/view?usp=sharing

**Comment by JeromeMartinez** [comment]
For reference, the 3 first points are:
- from sample offset 8191 to 2644725 (length of 2636534) , named "intro"
- from sample offset 2647070 to 2679739‬ (length of 32669), named "silence"
- from sample offset 2679719 to 19038161‬ (length of 16358442), named "Supreme court decision"

I note that there are gaps e.g. between start and point 1 there are 8191 unreferenced samples, between points 1 & 2 there are 2345 unreferenced samples, between points 2 & 3 there are 20 unreferenced samples.

We could have a "spreadsheet" with 1 line per cue point and columns for ID, start, length, name, a note (empty in the example), purpose ID, country, language, dialect, code page, "labeled text" content (empty in the example).
Would it make sense to warn if some samples are not referenced?

I don't see "a descriptive relationship to the metadata of the bext and LIST-INFO chunk", cue points seems not having any relationship with other LIST-INFO chunks.

Trace of the data used for the 3 first points:

```
220FDD7E  Cue points (396 bytes)
220FDD7E   Header (8 bytes)
220FDD7E    Name:                                cue 
220FDD82    Size:                                388 (0x00000184)
220FDD86   numCuePoints:                         16 (0x00000010)
220FDD8A   Cue point (24 bytes)
220FDD8A    ID:                                  1 (0x00000001)
220FDD8E    Position:                            8191 (0x00001FFF)
220FDD92    DataChunkID:                         data
220FDD96    ChunkStart:                          0 (0x00000000)
220FDD9A    BlockStart:                          0 (0x00000000)
220FDD9E    SampleOffset:                        8191 (0x00001FFF)
220FDDA2   Cue point (24 bytes)
220FDDA2    ID:                                  2 (0x00000002)
220FDDA6    Position:                            2647070 (0x0028641E)
220FDDAA    DataChunkID:                         data
220FDDAE    ChunkStart:                          0 (0x00000000)
220FDDB2    BlockStart:                          0 (0x00000000)
220FDDB6    SampleOffset:                        2647070 (0x0028641E)
220FDDBA   Cue point (24 bytes)
220FDDBA    ID:                                  3 (0x00000003)
220FDDBE    Position:                            2679719 (0x0028E3A7)
220FDDC2    DataChunkID:                         data
220FDDC6    ChunkStart:                          0 (0x00000000)
220FDDCA    BlockStart:                          0 (0x00000000)
220FDDCE    SampleOffset:                        2679719 (0x0028E3A7)
[...]
220FDF0A  Associated Data List (1078 bytes)
220FDF0A   Header (12 bytes)
220FDF0A    Name:                                LIST
220FDF0E    Size:                                1070 (0x0000042E)
220FDF12    Real Name:                           adtl
220FDF16   Label (18 bytes)
220FDF16    Header (8 bytes)
220FDF16     Name:                               labl
220FDF1A     Size:                               10 (0x0000000A)
220FDF1E    Cue Point ID:                        1 (0x00000001)
220FDF22    Text:                                intro
220FDF28   Label (20 bytes)
220FDF28    Header (8 bytes)
220FDF28     Name:                               labl
220FDF2C     Size:                               12 (0x0000000C)
220FDF30    Cue Point ID:                        2 (0x00000002)
220FDF34    Text:                                silence
220FDF3C   Label (36 bytes)
220FDF3C    Header (8 bytes)
220FDF3C     Name:                               labl
220FDF40     Size:                               27 (0x0000001B)
220FDF44    Cue Point ID:                        3 (0x00000003)
220FDF48    Text:                                Supreme court decision
220FDF5F    Alignement:                          (1 bytes)
[...]
220FE0A0   Note (14 bytes)
220FE0A0    Header (8 bytes)
220FE0A0     Name:                               note
220FE0A4     Size:                               5 (0x00000005)
220FE0A8    Cue Point ID:                        1 (0x00000001)
220FE0AC    Text:                                
220FE0AD    Alignement:                          (1 bytes)
220FE0AE   Note (14 bytes)
220FE0AE    Header (8 bytes)
220FE0AE     Name:                               note
220FE0B2     Size:                               5 (0x00000005)
220FE0B6    Cue Point ID:                        2 (0x00000002)
220FE0BA    Text:                                
220FE0BB    Alignement:                          (1 bytes)
220FE0BC   Note (14 bytes)
220FE0BC    Header (8 bytes)
220FE0BC     Name:                               note
220FE0C0     Size:                               5 (0x00000005)
220FE0C4    Cue Point ID:                        3 (0x00000003)
220FE0C8    Text:                                
220FE0C9    Alignement:                          (1 bytes)
[...]
220FE180   Labeled Text (28 bytes)
220FE180    Header (8 bytes)
220FE180     Name:                               ltxt
220FE184     Size:                               20 (0x00000014)
220FE188    Cue Point ID:                        1 (0x00000001)
220FE18C    Sample Length:                       2636534 (0x00283AF6)
220FE190    Purpose ID:                          rgn 
220FE194    Country:                             0 (0x0000)
220FE196    Language:                            0 (0x0000)
220FE198    Dialect:                             0 (0x0000)
220FE19A    Code Page:                           0 (0x0000)
220FE19C   Labeled Text (28 bytes)
220FE19C    Header (8 bytes)
220FE19C     Name:                               ltxt
220FE1A0     Size:                               20 (0x00000014)
220FE1A4    Cue Point ID:                        2 (0x00000002)
220FE1A8    Sample Length:                       32669 (0x00007F9D)
220FE1AC    Purpose ID:                          rgn 
220FE1B0    Country:                             0 (0x0000)
220FE1B2    Language:                            0 (0x0000)
220FE1B4    Dialect:                             0 (0x0000)
220FE1B6    Code Page:                           0 (0x0000)
220FE1B8   Labeled Text (28 bytes)
220FE1B8    Header (8 bytes)
220FE1B8     Name:                               ltxt
220FE1BC     Size:                               20 (0x00000014)
220FE1C0    Cue Point ID:                        3 (0x00000003)
220FE1C4    Sample Length:                       16358442 (0x00F99C2A)
220FE1C8    Purpose ID:                          rgn 
220FE1CC    Country:                             0 (0x0000)
220FE1CE    Language:                            0 (0x0000)
220FE1D0    Dialect:                             0 (0x0000)
220FE1D2    Code Page:                           0 (0x0000)
[...]
```

**Comment by MarcosSueiro** [comment]
In our case the fact that there are unreferenced samples is the norm, but others may find it useful.

A spreadsheet approach seems to be the most user-friendly. I attach Adobe's interface, which incidentally includes a non-editable "description" field which may not be part of the cue standard.

The ability to upload cue chunk data, along or separately from Core and XMP, would be useful.

I also do not find a connection with the LIST-INFO chunks. Adobe (at least) also documents cue markers (and many other things) in its XMP (enclosed).

Thanks

[AuditionCuesXMP.txt](https://github.com/MediaArea/BWFMetaEdit/files/4504761/AuditionCuesXMP.txt)

![AuditionMarkers](https://user-images.githubusercontent.com/521684/79774461-d5e4c600-8300-11ea-9b42-9fb2db68d61f.png)

**Comment by JeromeMartinez** [comment]
> I attach Adobe's interface, which incidentally includes a non-editable "description" field which may not be part of the cue standard.

Weird that it is not editable. Maybe when type is something else than "Cue"? anyway, if not useful, we don't do more than cues. But in the file we have 3 places for text: "label", "note" and "labeled text". Description of the fields is at [this website](https://sites.google.com/site/musicgapi/technical-documents/wav-file-format#list) for example.

> The ability to upload cue chunk data, along or separately from Core and XMP, would be useful.

Easy to do (import/export, in the GUI and in the CLI).

> Adobe (at least) also documents cue markers (and many other things) in its XMP (enclosed).

Argh, so we need to sync them. A bit more difficult but not impossible, we already do it for another item.

**Comment by MarcosSueiro** [comment]
I tried something other than cue in Audition but still could not edit the description.

I assume that in the picture 
      Name = "label"
      Description (non-editable) = "note"
since "labeled text" seems to have some further subfields such as purpose, country or language?

I think in our interview we requested import/export of Core/XMP/cue, but I do not see it as an issue. Should I add it?

We love XMP, esp XMP-dc, but syncing may be a whole other can of worms, although perhaps worth it?
[AuditionXMP.txt](https://github.com/MediaArea/BWFMetaEdit/files/4506140/AuditionXMP.txt)

**Comment by JeromeMartinez** [comment]
> I think in our interview we requested import/export of Core/XMP/cue, but I do not see it as an issue. Should I add it?

@dericed I let check how you organize the issues.

Just that for cue import/export in my mind it is part of this ticket, import/export of XMP is in my opinion already possible with the current GUI (click on "XMP" box, the popup window has the import and export buttons), and import/export of Core documents are in the menu. Need maybe a clarification.

> since "labeled text" seems to have some further subfields such as purpose, country or language?

Technically they are in the file, just zeroed in your file. We would have a UI for them.

> We love XMP, esp XMP-dc, but syncing may be a whole other can of worms, although perhaps worth it?

Edition of such XMP and sync between bext and other INFO chunk and XMP (you XMP contains a lot of copies of other INFO chunks) is in my opinion useful, now we need to prioritize development according to the dev budget we have + maybe another sponsor for too much specific and complex features. I let @dericed manage the priorities and budget.

**Comment by JeromeMartinez** [comment]
Development snapshot, with readout and export of the data (not yet edition): [Windows](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20201113-3/BWFMetaEdit_GUI_20.08.20201113_Windows_x64.exe), [macOS](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20201113-3/BWFMetaEdit_GUI_20.08.20201113_Mac.dmg), [others](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20201113-3/).
![Capture d%u2019écran du 2020-11-13 09-02-59](https://user-images.githubusercontent.com/1641638/99058053-ee6a4580-259c-11eb-8b53-bc2139a45787.png)

**Comment by MarcosSueiro** [comment]
I enclose some random WAVE files with markers and cues made with Audition for Mac, Fission, DSP-Quattro and Soundtrack Pro. Note that DSP-Quattro allows for loop markers, selections and markers.
[FADGIMarkerFiles.zip](https://github.com/MediaArea/BWFMetaEdit/files/5538229/FADGIMarkerFiles.zip)

**Comment by MarcosSueiro** [comment]
One more file, this one created in Wavelab, from our colleague Danny Sbardella.

https://drive.google.com/file/d/1jtUTjExm3BUYXXR80pCH7rzpBFYy_6UP/view?usp=sharing

Best,

Marcos

**Comment by JeromeMartinez** [comment]
@MarcosSueiro thanks! We'll use them for our tests.

**Comment by ablwr** [comment]
Hey @MarcosSueiro, there is a link to a test version of the cue chunk viewer and editor, if you are interested in giving it a try. It is linked in this issue: https://github.com/MediaArea/BWFMetaEdit/pull/192
