### ISSUE TITLE
Reject/warn of files with two WAVE chunks

### ISSUE THREAD

**Issue by MarcosSueiro** [MediaArea/BWFMetaEdit#109]
Occasionally files seem to present duplicate fields and have two WAVE chunks. Reject, warn, avoid creating. May be related to beginning/end data write option.

W:\ARCHIVESNAS1\INGEST\03 READY TO INGEST\Cooper Union Forum\WNYC-COOP-1969-uu-uu-152433.1 Symbolism.wav
00000000 7CE8C2E8 WAVE
0000000C 00000010      fmt 
00000024 7CE8A000      data
7CE8A02C 000002CE      WAVE
7CE8A302 00000495      iXML
7CE8A7A0 00001665      _PMX
7CE8BE0E 0000027A      INFO
7CE8BE1A 0000002E           IART
7CE8BE50 0000005E           ICMS
7CE8BEB6 00000078           ICMT
7CE8BF36 00000032           IKEY
7CE8BF70 00000016           IMED
7CE8BF8E 0000000E           ISFT
7CE8BFA4 00000042           ISRC
7CE8BFEE 00000068           ISRF
7CE8C05E 00000019           ITCH
7CE8C080 00000008           IGNR
7CE8C090 00000258      FLLR

**Comment by JeromeMartinez** [comment]
The easiest method is to reject the file, as it is invalid.
Is there any interest in supporting the edition of such file and/or fixing it?

**Comment by MarcosSueiro** [comment]
It would be interesting to know why this happens in the first place (perhaps related to crashes?). 

Fixing would be convenient, as otherwise one has to:

1. Save the file, without the metadata, in an external program as a new file
2. Copy each field from the old file to the new back in BWF ME (see also [this](https://github.com/MediaArea/BWFMetaEdit/issues/110))

Thanks!

**Comment by JeromeMartinez** [comment]
Just to be clear, the file having 2 WAVE chunks wasn't created by BWF MetaEdit, was it?

Here, a fix is to transform the 2nd WAVE chunk header to a JUNK chunk and modifying the first WAVE chunk in order to include the other chunks, creating a new file is not necessary.

**Comment by MarcosSueiro** [comment]
> Just to be clear, the file having 2 WAVE chunks wasn't created by BWF MetaEdit, was it?

I think it may have been --similar things have happened before. But I cannot be sure.

> Here, a fix is to transform the 2nd WAVE chunk header to a JUNK chunk and modifying the first 
WAVE chunk in order to include the other chunks, creating a new file is not necessary

Excellent! I assume no audio is lost?

**Comment by dericed** [comment]
The first WAVE at `00000000 7CE8C2E8 WAVE` is referencing the subformat of the RIFF chunk. I think to be more clear this should say `00000000 7CE8C2E8 RIFF(WAVE)`, since WAVE is just subformat of the RIFF chunk and not a chunk id in itself. I am curious here if the second `WAVE` is a chunk id or if there's another RIFF chunk. Also what's in that 2nd WAVE chunk?
