### ISSUE TITLE
CodingHist "save file" option doesn't work, also is not useful

### ISSUE THREAD

**Issue by ablwr** [MediaArea/BWFMetaEdit#122]
For CodingHist, users have the option to save or load text. Currently it's not working (for me, Ubuntu 18.04) or working incorrectly (for Dave, macOS, it saves the first line only).

Overall though, this feature doesn't provide a lot of value. I think instead of fixing it, it could be deprecated entirely. 

I think it's something involving the Load/Save file options in particular with CodingHist, because other segments with Import/Export do work successfully, when they are general text fields and not a specific form with dropdown menus. It probably has something to do with the strict required schema.

If anyone strongly disagrees, please sound off in the comments!!!

**Comment by dericed** [comment]
+1, for all fields that aren't xml.

**Comment by MarcosSueiro** [comment]
Subsequent file saves add tags, e. g. (**my bold**)

**M=M=M**=dual-mono,**T=T=**L side only. Occasional clipping.

**Comment by MarcosSueiro** [comment]
...but otherwise this is an AES-compliant, useful feature.
