### ISSUE TITLE
CodingHist "Mode" dropdown is too limited

### ISSUE THREAD

**Issue by ablwr** [MediaArea/BWFMetaEdit#123]
For `CodingHist`, the "Mode" dropdown is limited to only four options. The way around this, for users with different Modes, is to switch to the Free text box and edit it there. Is there a way to have the existing dropdown options and also an additional free text field option?

**Comment by dericed** [comment]
The `Mode` list comes from [EBU Technical Recommendation R98-1999](https://tech.ebu.ch/docs/r/r098.pdf). While the EBU document is a `recommendation` the vocabularies provided are listed as `allowed options`. Already in a few places, BWF MetaEdit adds values that are not allowed options, such as sample rate = 96000 or bit depth as 32. Describing audio which such terms makes sense but doesn't follow the EBU recommendation.

I suggest that the coding history drop-downs be condition according to what rules are followed:
- EBU R98-1999
- FADGI guidelines
- NO RULES!

The current FADGI guidelines are at http://www.digitizationguidelines.gov/audio-visual/documents/Embed_Guideline_20120423.pdf. There's some need for review here, for instance the FADGI guidelines cite EBU's list for sample rate, but then provide examples that don't follow it. Cc'ing @kmurmur as I think a FADGI recommendation update on this field would be helpful, given that the EBU recommendation is seemingly more obsolete.

**Comment by kmurmur** [comment]
Right - that's fair. We need to do an update on the FADGI guidelines to reflect changes in a few places. It's on my to do list...

**Comment by kmurmur** [comment]
So checking in on this as I'm working on updating the FADGI guidelines - are you waiting on me to provide extended values or is there already a list? Or will this be a text box instead? I'm struggling a bit to find published specs that go beyond 92 kHz (IASA says that can be used but is not intended to be a limit: https://www.iasa-web.org/tc04/key-digital-principles).  I feel comfortable including higher bc we are not recommending any specific value - just allowing for more values should they be used.

**Comment by retokromer** [comment]
When restoring sound elements, sometimes we – and, of course, others as well! – use values as high as 500 kHz. If I remember carefully, there was a presentation on this topic either at IASA or JTS last year in Hilversum: you probably remember better that I so. Yet, I know, that’s not a specification, more a reality.

**Comment by kmurmur** [comment]
Yes - I remember that. The published standards (IMHO) have not caught up to reality. :) FADGI doesn't make a recommendation about those values but our documentation shows only a limited set of values from EBU R98. I'll expand the values that would conform to the FADGI rule set to include up to 192.
