### ISSUE TITLE
CodingHist dropdown menus involve too many clicks

### ISSUE THREAD

**Issue by ablwr** [MediaArea/BWFMetaEdit#124]
When editing values in CodingHist, for some reason I have to double-click into the cell to get the dropdown menu to load. It would be better if a user didn't have to do that, and the drop-down menus would just appear without the need to double-click on them.

**Comment by JeromeMartinez** [comment]
@ablwr no more double click, it goes in "edition" mode now with a click, or a move (with keyboard) to the box, but not with e.g. a mouse over. Qt limitation, at least with default tool, I think it is not worth it to go further for the moment.

I build a snapshot soon.

**Comment by ablwr** [comment]
Thanks! I'll update the history with this and the other flurry of closed PRs from today.
