### ISSUE TITLE
XMP et al should at least be valid XML

### ISSUE THREAD

**Issue by ablwr** [MediaArea/BWFMetaEdit#125]
For XMP, aXML, iXML, it would be nice if these were minimally validated as XML. Would something like that be possible? It doesn't have to validate against their specs, but just check if there are open/closed tags and that all data is enclosed in them.

**Comment by JeromeMartinez** [comment]
We have [TinyXml](http://www.grinninglizard.com/tinyxml/) in Mediainfo, pretty small and it rejects invalid files. But it is a "yes/no" info, not indicating where is the issue.

**Comment by ablwr** [comment]
Right now in Tech view, if you add a random word into one of these fields, it'll change to "yes". Maybe we can keep it as "No" and turn it orange to let users know it's a problem?
