### ISSUE TITLE
Users cannot copy-paste between fields

### ISSUE THREAD

**Issue by ablwr** [MediaArea/BWFMetaEdit#133]
Similar to the points raised in https://github.com/MediaArea/BWFMetaEdit/issues/104:

Adding data can be cumbersome, requiring several clicks. Several users have requested that they have the ability to copy and paste across cells, much like in spreadsheet software like LibreCalc or Excel. 

@JeromeMartinez Is this possible? I can't quite tell from the feedback received in #104.

**Comment by lamacchiacosta** [comment]
It could also be a menu function, where we can choose to copy specific fields to other kind of metadata, for instance the BEXT comment could be copied also to the iXML comment field, the creation date to the ICRD and iXML relative field, and so on.
