### ISSUE TITLE
crash when scrolling to the end of list

### ISSUE THREAD

**Issue by lamacchiacosta** [MediaArea/BWFMetaEdit#149]
When I have a list of files, in File window, scrolling to the end will freeze and crash BWFMetaedit, with the only option for me to force quit to start again.
Mac OS 10.14.6, BWF Metaedit 20.05

**Comment by JeromeMartinez** [comment]
@lamacchiacosta please test [this snapshot](https://old.mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20200629-2/BWFMetaEdit_GUI_20.05.20200629_Mac.dmg).

**Comment by lamacchiacosta** [comment]
Hi Jérôme,

it's good so far. I loaded a list of files, went to the bottom and 
didn't experience the freeze behaviour.

Thanks for fixing it.

Emanuele
