### ISSUE TITLE
Inconsistent handling of non EBU R98 coding history values

### ISSUE THREAD

**Issue by privatezero** [MediaArea/BWFMetaEdit#150]
Using slightly non EBU R98 Compliant values in coding history is resulting in diverging behaviors within the GUI. When viewing a file that contains the value `A=ANALOG` (using all caps US spelling) the editor will default to freetext mode and warn that the value is not complaint due to the US vs UK spelling difference. This seems a good way to handle this situation.

However, when opening a file that contains `A=Analog` (US spelling and not upper-case) the viewer will default to the dropdown mode and erase that field entirely upon switching over to the plain text view (Unless a compliant value is selected). It seems that this would be another instance where defaulting to plain text view and warning about compliance would be beneficial. (Along with perhaps expanding accepted FADGI values to take regional spellings into account).

File containing `A=Analog,M=mono,T=Etc.`  defaults to this:
![bwf-example1](https://user-images.githubusercontent.com/12941699/85629363-98fdbe00-b626-11ea-8572-ea799803c831.png)
Which leads to this:
![bwf-example2](https://user-images.githubusercontent.com/12941699/85629371-9b601800-b626-11ea-81e1-65cfc43b7e5c.png)

**Comment by JeromeMartinez** [comment]
We already have some handling of regional spellings, but we need to improve it a bit, as well as handling well lower/upper-case stuff.

**Comment by JeromeMartinez** [comment]
@privatezero please test [this snapshot](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20200625/).

**Comment by privatezero** [comment]
Works great! Thank you!
