### ISSUE TITLE
add a test to ensure data size is a proper value

### ISSUE THREAD

**Issue by dericed** [MediaArea/BWFMetaEdit#156]
`mod ( data_chunk_size , channel_count * bytes_per_sample )` MUST equal 0, else show a warning

**Comment by JeromeMartinez** [comment]
if format is PCM (bext chunk is intended for PCM, but can be found with compressed content).

**Comment by dericed** [comment]
true, thanks @JeromeMartinez. I was chatting with @privatezero about fixing some samples with the padding byte error mentioned in an earlier ticket. We considered adding 1 to the data size, but that would create a 1/3 of a sample. I'm unclear if any underlying documentation disallows partial samples, thus i suggest this is a warning rather than an error.

**Comment by JeromeMartinez** [comment]
> I'm unclear if any underlying documentation disallows partial samples

The other ticket is not yet clear to me (I'll check more later), but I am pretty sure that creating 1/3 of a sample is not a good direction, and is not expected by spec designers.

**Comment by dericed** [comment]
Here's a sample file with that error [data_length_not_sample_aligned.wav.zip](https://github.com/MediaArea/BWFMetaEdit/files/5012645/data_length_not_sample_aligned.wav.zip).
