### ISSUE TITLE
release time :)

### ISSUE THREAD

**Issue by dericed** [MediaArea/BWFMetaEdit#165]
Lots of updates since last time and a few pull requests ready to go.

@ablwr, any last minute suggestions to squeeze in? Can you update the the release notes?
@JeromeMartinez, @g-maxime, ready for a new release?

Particularly excited about copy/paste.

**Comment by ablwr** [comment]
Will do! I haven't given it a test run in a while so I'll do that and collect changes.

**Comment by ablwr** [comment]
I will send a PR for the history.txt, but in Markdown, here:

Release notes:

* Users can copy/paste between fields (Issue [#133](https://github.com/MediaArea/BWFMetaEdit/issues/133))
* Fix compilation issues with non Unicode on Windows (Issue [#135](https://github.com/MediaArea/BWFMetaEdit/issues/135))
* Fix crash when scrolling to end of File view (Issue [#149](https://github.com/MediaArea/BWFMetaEdit/issues/149))
* XMP, aXML, iXML is valid XML (Issue [#125](https://github.com/MediaArea/BWFMetaEdit/issues/125))
* Add option to show address and size as decimal values in trace view (Issue [#152](https://github.com/MediaArea/BWFMetaEdit/issues/152))
* Expand verbosity of truncation errors (Issue [#95](https://github.com/MediaArea/BWFMetaEdit/issues/95))
* Add sorting options for filename column in tables views (Issue [#96](https://github.com/MediaArea/BWFMetaEdit/issues/96))
* Allow numerical table sorting (Issue [#97](https://github.com/MediaArea/BWFMetaEdit/issues/97))
* Handle non-EBU R98 coding history values (Issue [#150](https://github.com/MediaArea/BWFMetaEdit/issues/150))

**Comment by ablwr** [comment]
Before I do that though, I gave this a quick smoke test. 

For me testing the latest build (0801) on Ubuntu 18.04, the `File` view does not load for me. I can see files loaded in the other two views.

For me, checking the decimal values for Trace view doesn't seem to be working (not with new files, or restarting BWFME with it checked and trying again).

So other than thatttttt:
Copy/pasting is working great, can't test the Unicode/Windows thing, I do get XML parsing/quick validation, sorting is improved, CodingHist regional differences is improved.

**Comment by dericed** [comment]
@ablwr, for decimal views, did you see the toggle button in the Preferences tab? Worked for me but I build from the PR's branch, perhaps the daily builds aren't recent enough to include that.

**Comment by ablwr** [comment]
@dericed Yeah, that was the only place I saw to change that setting and that's what I tried. I can try building from master or waiting for a new daily build.

I see new updates coming through, so I will update the above comment's list.

**Comment by g-maxime** [comment]
@ablwr @dericed please test [this snapshot](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20200803-4/), in order to catch any remaining nasty bug.

**Comment by JeromeMartinez** [comment]
@ablwr @dericed is it OK now for a release? @g-maxime would add the release notes in the PR of version change.

**Comment by ablwr** [comment]
The File view issue I had is no longer present in the latest snapshot!

**Comment by dericed** [comment]
let's go!
