### ISSUE TITLE
Scanning and exporting as CSV

### ISSUE THREAD

**Issue by Tim2460** [MediaArea/BWFMetaEdit#191]
Hello team : 
If i MediaInfo scan an entire directory and export as csv i have a problem : 
If the very first file scanned is an MKV, no problem as every file after that one is scanned and exported fine, if possible.
If the very first file scanned is an .iso, or .srt or .idx, every file on the dir is scanned, but the exported csv is arounf 1/3 the normal size, with a lot of collums info missing on the output.

I save the export as csv with the default output (2 streams and 2 subs max).

When everything ok the output collums goes Up to "Audio 1   Encryption", 431 collums

If i meet the bug, the collum goes to "General   Played_Count", 178 collums only

So i have 90% of my outputs as 431 collums ... and 10% as 178 ...

Got to remake all the smaller output ones.

Bug should be easy to recreate i guess, i'm using version "MediaInfo 20.09".

**Comment by JeromeMartinez** [comment]
If I understand well, you speak only about MediaInfo, and not about BWF MetaEdit, so the issue should be on https://github.com/MediaArea/MediaInfo/issues
