### ISSUE TITLE
GUI: file-loading progress meter functionality has decreased in recent versions

### ISSUE THREAD

**Issue by affoh** [MediaArea/BWFMetaEdit#194]
In older version such as 1.3.8, whether you are opening a single file or a batch, you immediately get feedback that files are loading by the progress bar popping up immediately. 

After upgrading to 20.08, no longer do you get that information. In Windows 10, there is a considerable delay, then the application says "not responding" as if something is wrong. In MacOS 10.13.6 I get the same delay and then the spinning wheel appears until it's 99% loaded and then the progress meter flashes on the screen for a split second before displaying the data. It does function slightly better when loading in multiple files, but not as well as before. For instance there is still a delay and the meter is lagging when it finally opens. 

It is helpful to see that the application is working on the task and to be able to project how long it will take.

**Comment by JeromeMartinez** [comment]
Regression, this was not wanted, we'll check and put the feature back.
