### ISSUE TITLE
Allow complete export of all chunks under one master xml: Core, Tech, Cue

### ISSUE THREAD

**Issue by MarcosSueiro** [MediaArea/BWFMetaEdit#196]

**Comment by MarcosSueiro** [comment]
Please please please implement this.... It would be amazing to have one structured master document with all of the that wav's supported chunks:

`<RDF>
<Tech> [data...] </Tech>
<Core> [data...] </Core>
<Cue> [data...] </Cue>
etc... (all supported chunks)
</RDF>`

Thank you!!!

**Comment by JeromeMartinez** [comment]
It is in the pipe :).

**Comment by MarcosSueiro** [comment]
A W E S O M E
Thank you!!

**Comment by MarcosSueiro** [comment]
Additional thoughts:

It may be very useful to organize the chunk display in the order they appear in the file, mimicking the wonderful "Trace" view.

An RDF output may useful, where you flatten the xml tree where you can and instead use namespaces. This is how exiftool does it, and it works well: 

`<rdf:Description rdf:about='W:/ARCHIVESNAS1/INGEST/01 PLEASE REVIEW/Levy/20201215Memnon/20201215NewSounds/WNYC-NSDS-2002-09-06-34228.3 New Sounds Pgm 1952.wav'
  xmlns:et='http://ns.exiftool.ca/1.0/' et:toolkit='Image::ExifTool 11.69'
  xmlns:ExifTool='http://ns.exiftool.ca/ExifTool/1.0/'
  xmlns:System='http://ns.exiftool.ca/File/System/1.0/'
  xmlns:File='http://ns.exiftool.ca/File/1.0/'
  xmlns:RIFF='http://ns.exiftool.ca/RIFF/RIFF/1.0/'
  xmlns:Composite='http://ns.exiftool.ca/Composite/1.0/'>
 <ExifTool:ExifToolVersion>11.69</ExifTool:ExifToolVersion>
 <System:FileName>WNYC-NSDS-2002-09-06-34228.3 New Sounds Pgm 1952.wav</System:FileName>
 <System:Directory>W:/ARCHIVESNAS1/INGEST/01 PLEASE REVIEW/Levy/20201215Memnon/20201215NewSounds</System:Directory>
 <System:FileSize>2.1 GB</System:FileSize>
 <System:FileModifyDate>2021:01:05 14:35:21-05:00</System:FileModifyDate>
 <System:FileAccessDate>2021:01:05 14:35:21-05:00</System:FileAccessDate>
 <System:FileCreateDate>2020:12:31 08:16:40-05:00</System:FileCreateDate>
 <System:FilePermissions>rw-rw-rw-</System:FilePermissions>
 <File:FileType>WAV</File:FileType>
 <File:FileTypeExtension>wav</File:FileTypeExtension>
 <File:MIMEType>audio/x-wav</File:MIMEType>
 <RIFF:Encoding>Extensible</RIFF:Encoding>
 <RIFF:NumChannels>2</RIFF:NumChannels>
 <RIFF:SampleRate>96000</RIFF:SampleRate>
 <RIFF:AvgBytesPerSec>576000</RIFF:AvgBytesPerSec>
 <RIFF:BitsPerSample>24</RIFF:BitsPerSample>
 <RIFF:Description>WNYC-NSDS-2002-09-06-34228.3 New Sounds Pgm 1952</RIFF:Description>
 <RIFF:Originator>Memnon Archiving</RIFF:Originator>
 <RIFF:OriginatorReference></RIFF:OriginatorReference>
 <RIFF:DateTimeOriginal></RIFF:DateTimeOriginal>
 <RIFF:TimeReference>0</RIFF:TimeReference>
 <RIFF:BWFVersion>0</RIFF:BWFVersion>
 <RIFF:BWF_UMID>0000000000000000000000000000000000000000000000000000000000000000</RIFF:BWF_UMID>
 <RIFF:CodingHistory>A=ANALOG,T=A807-08
A=PCM,F=96000,W=24,M=stereo,T=MIS-AUDIO-02-03
</RIFF:CodingHistory>
 <RIFF:ArchivalLocation>US, WNYC</RIFF:ArchivalLocation>
 <RIFF:Commissioned>http://id.loc.gov/authorities/names/n85360545 ; http://id.loc.gov/authorities/names/n81047053</RIFF:Commissioned>
 <RIFF:Copyright>Terms of Use and Reproduction: WNYC Radio. Additional copyright may apply to musical selections.</RIFF:Copyright>
 <RIFF:DateCreated>2002:09:06</RIFF:DateCreated>
 <RIFF:Genre>Music talk</RIFF:Genre>
 <RIFF:Keywords>http://id.loc.gov/authorities/subjects/sh85088762</RIFF:Keywords>
 <RIFF:Medium>1/4 inch audio tape 34228.2</RIFF:Medium>
 <RIFF:Product>New Sounds</RIFF:Product>
 <RIFF:Software>Memnon Audio Ingest System</RIFF:Software>
 <RIFF:Source>https://cavafy.wnyc.org/assets/42afbc07-3e86-48a2-a8f6-9ed61b825b72</RIFF:Source>
 <RIFF:Technician>mawtobey, Memnon Archiving</RIFF:Technician>
 <Composite:Duration>1:05:54</Composite:Duration>
</rdf:Description>`


(Sorry about the lack of indents)

**Comment by MarcosSueiro** [comment]
Also: output error-check results
