### ISSUE TITLE
Documentation on ICMT rules

### ISSUE THREAD

**Issue by MarcosSueiro** [MediaArea/BWFMetaEdit#198]
Documentation on rules is incorrect (although I think implementation is correct).

In http://bwfmetaedit.sourceforge.net/validation_rules_help.html

where it says 

 ICMD: The ICMD field must not contain line breaks. 

it should say 

 ICMT: The ICMT field must not contain line breaks. 

See https://www.aelius.com/njh/wavemetatools/doc/riffmci.pdf

**Comment by g-maxime** [comment]
New documentation URL : https://mediaarea.net/BWFMetaEdit
