### ISSUE TITLE
verbosity of --MD5-Verify in CLI vs GUI

### ISSUE THREAD

**Issue by privatezero** [MediaArea/BWFMetaEdit#203]
Right now there is a disconnect in verbosity of outputs for MD5 verification between the CLI and the GUI tools. In GUI if you attempt to verify a file that does not have an MD5 embedded it will display `MD5, no existing MD5 chunk` in the information field. Likewise, if the MD5 file verifies it displays `MD5, Verified`

When the command `bwfmetaedit --MD5-Verify` is run on targets in the CLI it outputs a new line (blank space) for both files where MD5s verify and where there are no embedded MD5s, with the only clear output being in the event of a fail. This effectively makes it impossible to use the CLI to validate MD5s as it only gives meaningful output in the event of a fail, without allowing any distinction between other possible outcomes.

![image](https://user-images.githubusercontent.com/12941699/110545517-15b3c800-80e2-11eb-9fdb-ff6c98e8d9e1.png)

**Comment by g-maxime** [comment]
You can get the same output as with the GUI with the --verbose (-v) option
