### ISSUE TITLE
CLI --MD5-Verify exit status

### ISSUE THREAD

**Issue by privatezero** [MediaArea/BWFMetaEdit#204]
This is related to  https://github.com/MediaArea/BWFMetaEdit/issues/203, but seemed to fall more into the realm of a potential enhancement so I figured it should be a separate issue.

For the command `bwfmetaedit --MD5-Verify file.wav` all of the possible outcomes exit with a status of `0`. It seems like it might be worth only exiting with `0` if the MD5 validates and exiting with non zero in the event of a bad or missing MD5.

This would greatly aid in the integration of bwfmetaedit in batch scripts (which seems like a likely use case for the CLI) and would be more in line with typical behavior of other hash validating tools.

**Comment by JeromeMartinez** [comment]
@g-maxime please check, and adapt if needed, that when there is a validation error (MD5 or something else), return value is not 0.

**Comment by privatezero** [comment]
Thanks a ton for this! Looking forward to testing it out

**Comment by JeromeMartinez** [comment]
> Looking forward to testing it out

[Latest snasphot](https://mediaarea.net/download/snapshots/binary/bwfmetaedit/20210413-2/).

**Comment by privatezero** [comment]
Tested latest on Ubuntu 20.04 and works like a charm! This will be great for integrating bwfmetaedit more into loop validation scripts. Thanks again!
