### ISSUE TITLE
21.07-new coding history behavior or bug?

### ISSUE THREAD

**Issue by affoh** [MediaArea/BWFMetaEdit#223]
Getting the “malformed input” error when the rule is checked in preferences for EBU R98 for 96000 kHz files with pre-populated bext chunks/coding histories. When checked, the options for sampling frequency only goes to 88200, hence the error. When you uncheck the rule, you get up to 768000 (all the new stuff). Is that how it is supposed to behave? For instance in version 20.08 the choices of sampling frequency go to 96000 whether or not the rule is checked.

**Comment by g-maxime** [comment]
R98-1999 Allows samplings frequencies only up to 48000 https://tech.ebu.ch/docs/r/r098.pdf

For me, the bug is the presence of 64000 and 88200 in the list when the rule is checked.
And the error message needs to be reworked to include more informations.

**Comment by JeromeMartinez** [comment]
IMO we should adapt to "modern" sample rates like 96k, it is legitimate. And maybe 768k etc. @kmurmur?

**Comment by kmurmur** [comment]
Yes - for the FADGI rule set,  we adopted sample rates beyond R98 which is too limited for some contemporary workflows.

**Comment by kmurmur** [comment]
From the Guidelines: 
Adding values for sampling frequency, bit depth and mode beyond what is listed in EBU R98 to reflect current needs and tool capabilities
Added values for sampling frequency: 96000, 176400, 192000, 384000, 768000 Hz
Added value for word length/bit depth: 32 bits

**Comment by affoh** [comment]
Thanks for the feedback all! I did see the new FADGI guideline on that but was a bit confused since the behavior changed from previous versions. EBUR98 only goes to 48 but the list allowed selections to 96k. Now the list is limited based on selection. For now, unchecking the rule seems the way to proceed.
