### ISSUE TITLE
Coding History Mode Drop-Downs

### ISSUE THREAD

**Issue by knfleck** [MediaArea/BWFMetaEdit#225]
Hey! 

I went to review the drop-downs for the modes in the coding history (version 21.07 - Windows 10) and saw that there are only four modes: mono, stereo, dual-mono, and joint-stereo. Just wanted to ask about this because the new guidelines also mention multitrack, multichannel, and other. I could be missing something though! :) 

Thanks!

Cheers, 
Karl

**Comment by JeromeMartinez** [comment]
FADGI guidelines conflict with BWF CodigHistory specs (which are old...), so we don't show (but you can manually fill the values) the FADGI values when BWF CodigHistory recommendations are checked or when FADGI recommendations are not checked in the preferences (rules tab).

**Comment by knfleck** [comment]
OK, I just clicked the FADGI recommendations in the preferences and I can see the additional modes now. I should've had that checked all along (d'oh). Thank you!!

**Comment by g-maxime** [comment]
Additional FADGI modes added by #209.
Also, the field allows custom value if not rules are checked (#176).

Closing as completed, feel free to re-open if you think it's still an issue.
