### ISSUE TITLE
Crash when de-selecting UMID

### ISSUE THREAD

**Issue by MarcosSueiro** [MediaArea/BWFMetaEdit#226]
I have 63 files open. When I select Options > Temporary Preferences > Core > and deselect UMID, BWFME crashes.

**Comment by MarcosSueiro** [comment]
Not so when I select Options > Preferences > and deselect UMID in the Core Metadata tab.

**Comment by g-maxime** [comment]
I've found a random crash when menu is updated, may be related to this issue.
Please try [this snapshot](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20210922-2)
