### ISSUE TITLE
unifed xml comments

### ISSUE THREAD

**Issue by dericed** [MediaArea/BWFMetaEdit#245]
1. For `ffmpeg -f lavfi -i sine -t 1 hey.wav` and many others, I get an xml with `bwfmetaedit --out-xml hey.wav` that includes:

```
            <Information>
</Information>
```

Can this be `<Information/>` instead as I suspect the line break is meaningless here?

2.  Please add `/File/Technical/UnsupportedChunks`

**Comment by g-maxime** [comment]
"UnsupportedChunks" is present when non-empty:
`<UnsupportedChunks>MJTU</UnsupportedChunks>`

Same for "Information" after fix.

**Comment by dericed** [comment]
thx :)
