### ISSUE TITLE
Incorrect Codec ID in GUI

### ISSUE THREAD

**Issue by MarcosSueiro** [MediaArea/BWFMetaEdit#249]
Codec shows correctly as FFFE in the CLI, but as 0001 in the GUI... See below

A test file is [here](https://drive.google.com/file/d/1Nqcu2u40vJPKDfqOz9CGOAky7h_gVqJa/view?usp=sharing).
```
C:\mySoftware>bwfmetaedit --out-tech "W:\ARCHIVESNAS1\INGEST\01 PLEASE REVIEW\codec_and_channel_layout_questions\WQXR-YAS-1973-12-12-600083.2 Joseph Piorine_COPY.wav"
FileName,FileSize,Format,CodecID,Channels,SampleRate,BitRate,BitPerSample,Duration,UnsupportedChunks,bext,INFO,Cue,XMP,aXML,iXML,MD5Stored,MD5Generated,Errors,Information
W:\ARCHIVESNAS1\INGEST\01 PLEASE REVIEW\codec_and_channel_layout_questions\WQXR-YAS-1973-12-12-600083.2 Joseph Piorine_COPY.wav,1469153918,Wave,FFFE,1,96000,2304000,24,01:25:01.206,,Version 1,Yes,No,Yes,No,No,EC2DA8B77618AB07996663AAADEE7388,,,
```
![WrongCodecIDInBWFMEGUI](https://user-images.githubusercontent.com/521684/222828276-a86d6cc5-b39b-40f8-ad44-a22719da2aa4.png)

**Comment by g-maxime** [comment]
> Codec shows correctly as FFFE in the CLI
[This isn't supposed to](https://github.com/MediaArea/BWFMetaEdit/commit/36e276a517f295eca1b028f51bc2c97256ffbf83). Is the CLI up to date? 

> but as 0001 in the GUI... See below
0001 come from the  subformat  when format is set to WAVE_FORMAT_EXTENSIBLE
