### ISSUE TITLE
Project should have a .gitignore and/or provisions for out-of-tree builds

### ISSUE THREAD

**Issue by fenugrec** [MediaArea/BWFMetaEdit#262]
To make development easier , a .gitignore would be nice to filter out compilation byproducts (*.o , MOC stuff etc).

Ability to compile out-of-tree (or as a subdirectory) would also help keep the source tree clean.

**Comment by JeromeMartinez** [comment]
We have a [.cvsignore](https://github.com/MediaArea/BWFMetaEdit/blob/master/.cvsignore) due to history and we whould definitely move to  .gitignore and possibility of subdirectory, at long term.

**Comment by fenugrec** [comment]
Thanks, hadn't noticed it.

Is there any interest to moving to a higher-level build system (e.g. cmake or other) ?
