### ISSUE TITLE
`--out-cue-xml` not working as expected

### ISSUE THREAD

**Issue by fenugrec** [MediaArea/BWFMetaEdit#265]
built from latest master (906d0148ff89e5367abfadc760c8d86659970f9a) , behaviour is strange and depends on the order of args :

```
$ ./bwfmetaedit  <filename.wav> --out-cue-xml
Only one input file is allowed for the output(s): --out-cue=

$ ./bwfmetaedit --out-cue-xml <filename.wav>
...... prints the XML to stdout, no error message, no attempt to create filename.wav.xml
```

As I understand, `--out-cue-xml` should create a new .xml file with the cue points ?  seems like CLI args are maybe not parsed correctly, unless I'm using it wrong...

**Comment by JeromeMartinez** [comment]
Latest [snapshots](https://mediaarea.net/download/snapshots/binary/) includes the fix.
