### ISSUE TITLE
How does one insert Technical Metadata into a BWF file? `--in-tech` options aren't yet available.

### ISSUE THREAD

**Issue by npinto** [MediaArea/BWFMetaEdit#272]
`--out-tech` is available to export Technical Metadata, and I would like to import that data as well, the same way I can import aXML with `--in-aXML=`. How would one achieve that?

Thanks for your help.

**Comment by g-maxime** [comment]
Most technical metadata are read-only. You can modify the XMLs, BEXT version and md5sum through their respective flags:
--in-XMP=
--in-aXML=
--in-iXML=
--in-cue=
--BextVersion= 
--MD5-Embed

If you believe any other chunk should be editable, please specify your requirements.

**Comment by npinto** [comment]
Thanks for your answer. So I guess `tech` is read-only and inferred from the file itself? If so, then there is no need to edit it.

**Comment by JeromeMartinez** [comment]
> So I guess tech is read-only and inferred from the file itself?

Channel count, sample rate, etc, are technical information and not metadata. They could be changed, with limits e.g. you may change the sampling rate from 44k to 48k but in that case the resulting audio content would be different.

>  If so, then there is no need to edit it.

Closing the ticket, let us know if there would be something not editable but relevant to edit from your point of view.
