### ISSUE TITLE
crash on launch with 24.01 on mac0s 13.1 on Intel mac

### ISSUE THREAD

**Issue by dericed** [MediaArea/BWFMetaEdit#282]
------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               BWF MetaEdit [11193]
Path:                  /Applications/BWF MetaEdit.app/Contents/MacOS/BWF MetaEdit
Identifier:            net.mediaarea.bwfmetaedit.mac
Version:               24.01 (24.01)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2024-02-08 14:29:29.3287 -0500
OS Version:            macOS 13.1 (22C65)
Report Version:        12
Bridge OS Version:     7.2 (20P3045)
Anonymous UUID:        E6B5745B-F375-4145-2560-235BC1C660D6

Time Awake Since Boot: 970 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 4 Symbol missing
Symbol not found: __ZTVNSt3__13pmr25monotonic_buffer_resourceE
Referenced from: <148647EA-B59F-34F8-A0D3-B9ECA59AFA6A> /Applications/BWF MetaEdit.app/Contents/MacOS/BWF MetaEdit
Expected in:     <5C425EA0-066D-38B9-9DB4-8D3885D78B6B> /usr/lib/libc++.1.dylib
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                              0x7ff80d28fb4a __abort_with_payload + 10
1   dyld                              0x7ff80d2a8d07 abort_with_payload_wrapper_internal + 82
2   dyld                              0x7ff80d2a8d39 abort_with_payload + 9
3   dyld                              0x7ff80d2301e1 dyld4::halt(char const*) + 375
4   dyld                              0x7ff80d22d660 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4502
5   dyld                              0x7ff80d22c281 start + 2289

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b4af32a8  rdx: 0x00007ff7b4af3710
  rdi: 0x0000000000000006  rsi: 0x0000000000000004  rbp: 0x00007ff7b4af32f0  rsp: 0x00007ff7b4af32a8
   r8: 0x00007ff7b4af3310   r9: 0x0000000000000000  r10: 0x0000000000000094  r11: 0x0000000000000246
  r12: 0x0000000000000094  r13: 0x00007ff7b4af3710  r14: 0x0000000000000004  r15: 0x0000000000000006
  rip: 0x00007ff80d28fb4a  rfl: 0x0000000000000246  cr2: 0x000000010d016000
 
Logical CPU:     0
Error Code:      0x02000209
Trap Number:     133

Binary Images:
    0x7ff80d226000 -     0x7ff80d2bac6f dyld (*) <bb7a0970-8c62-3dce-a7a2-5cec9c501f11> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=413.7M resident=0K(0%) swapped_out_or_unallocated=413.7M(100%)
Writable regions: Total=8804K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8804K(100%)

                                VIRTUAL   REGION
REGION TYPE                        SIZE    COUNT (non-coalesced)
===========                     =======  =======
STACK GUARD                       56.0M        1
Stack                             8192K        1
VM_ALLOCATE                          8K        2
__DATA                            15.8M      271
__DATA_CONST                      13.1M      170
__DATA_DIRTY                       623K       95
__FONT_DATA                        2352        1
__LINKEDIT                       182.3M        3
__OBJC_RO                         65.4M        1
__OBJC_RW                         1988K        2
__TEXT                           231.4M      292
dyld private memory                512K        2
shared memory                        4K        1
===========                     =======  =======
TOTAL                            575.1M      842

-----------
Full Report
-----------

{"app_name":"BWF MetaEdit","timestamp":"2024-02-08 14:29:29.00 -0500","app_version":"24.01","slice_uuid":"148647ea-b59f-34f8-a0d3-b9eca59afa6a","build_version":"24.01","platform":1,"bundleID":"net.mediaarea.bwfmetaedit.mac","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.1 (22C65)","roots_installed":0,"name":"BWF MetaEdit","incident_id":"C3789EB3-6C4B-4D74-9618-21E10AD82240"}
{
  "uptime" : 970,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro15,2",
  "coalitionID" : 1433,
  "osVersion" : {
    "train" : "macOS 13.1",
    "build" : "22C65",
    "releaseType" : "User"
  },
  "captureTime" : "2024-02-08 14:29:29.3287 -0500",
  "incident" : "C3789EB3-6C4B-4D74-9618-21E10AD82240",
  "pid" : 11193,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-02-08 14:29:29.3117 -0500",
  "procStartAbsTime" : 970970571773,
  "procExitAbsTime" : 970986472277,
  "procName" : "BWF MetaEdit",
  "procPath" : "\/Applications\/BWF MetaEdit.app\/Contents\/MacOS\/BWF MetaEdit",
  "bundleInfo" : {"CFBundleShortVersionString":"24.01","CFBundleVersion":"24.01","CFBundleIdentifier":"net.mediaarea.bwfmetaedit.mac"},
  "storeInfo" : {"deviceIdentifierForVendor":"ED582067-576F-5D54-BB99-BD378F162C86","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "net.mediaarea.bwfmetaedit.mac",
  "crashReporterKey" : "E6B5745B-F375-4145-2560-235BC1C660D6",
  "throttleTimeout" : 2147483647,
  "bridgeVersion" : {"build":"20P3045","train":"7.2"},
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":4,"flags":518,"namespace":"DYLD","indicator":"Symbol missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Symbol not found: __ZTVNSt3__13pmr25monotonic_buffer_resourceE","Referenced from: <148647EA-B59F-34F8-A0D3-B9ECA59AFA6A> \/Applications\/BWF MetaEdit.app\/Contents\/MacOS\/BWF MetaEdit","Expected in:     <5C425EA0-066D-38B9-9DB4-8D3885D78B6B> \/usr\/lib\/libc++.1.dylib"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":46485,"threadState":{"r13":{"value":140701865031440},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":4},"rsi":{"value":4},"r8":{"value":140701865030416},"cr2":{"value":4513161216},"rdx":{"value":140701865031440},"r10":{"value":148},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":140703349406538,"matchesCrashFrame":1},"rbp":{"value":140701865030384},"rsp":{"value":140701865030312},"r12":{"value":148},"rcx":{"value":140701865030312},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":432970,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":535815,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":0},{"imageOffset":535865,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":41441,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":0},{"imageOffset":30304,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4502,"imageIndex":0},{"imageOffset":25217,"symbol":"start","symbolLocation":2289,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703348973568,
    "size" : 609392,
    "uuid" : "bb7a0970-8c62-3dce-a7a2-5cec9c501f11",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703348367360,
  "size" : 21474836480,
  "uuid" : "ea7f9772-219e-3ece-a4d9-20aeee3bc80f"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=413.7M resident=0K(0%) swapped_out_or_unallocated=413.7M(100%)\nWritable regions: Total=8804K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8804K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                            15.8M      271 \n__DATA_CONST                      13.1M      170 \n__DATA_DIRTY                       623K       95 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       182.3M        3 \n__OBJC_RO                         65.4M        1 \n__OBJC_RW                         1988K        2 \n__TEXT                           231.4M      292 \ndyld private memory                512K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                            575.1M      842 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "62b4513af75dc926494899c6",
      "factorPackIds" : {
        "COREOS_ICD" : "62fbe3cfa9a700130f60b3ea"
      },
      "deploymentId" : 240000019
    },
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro15,2, BootROM 1916.80.2.0.0 (iBridge: 20.16.3045.0.0,0), 4 processors, Quad-Core Intel Core i5, 2.4 GHz, 16 GB, SMC
Graphics: Intel Iris Plus Graphics 655, Intel Iris Plus Graphics 655, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, LPDDR3, 2133 MHz, SK Hynix, H9CCNNNCLGALAR-NVD
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, LPDDR3, 2133 MHz, SK Hynix, H9CCNNNCLGALAR-NVD
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Sep 14 2022 18:10:05 version 9.30.489.3.32.5.84 FWID 01-31bf0e8d
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: T2Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5

**Comment by g-maxime** [comment]
Please test [this snapshot](https://old.mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20240208-2/BWFMetaEdit_GUI_24.01.20240208_Mac.dmg)

**Comment by g-maxime** [comment]
Fixed in  24.05 and snapshots
