### ISSUE TITLE
Does not close multiple files

### ISSUE THREAD

**Issue by MarcosSueiro** [MediaArea/BWFMetaEdit#284]
- Selecting e.g. three files and then File - > Close 3 Files ... only closes the last one.
- Closing a single file or all files still works

**Comment by g-maxime** [comment]
Unable to reproduce this bug with the latest snapshot:  https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20240915-2/

Please check

**Comment by JeromeMartinez** [comment]
Closing as we can not reproduce.
