### ISSUE TITLE
Improve progress bar reporting

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/BWFMetaEdit#285]
Often 49% and then 100%... Later.
Open (often freeze with Open) and save.

**Comment by mwidzinski** [comment]
Software struggles when opening a large number of files at once. For example, when opening 32 hour-long wav files at 24bit/96kHz (~28 GB), the software will go into (Not Responding), but will eventually open them if you wait. Opening files progress bar sometimes will hang at 49%, then finished, but will not show actual progress. I will give the caveat that the progress bar has been performing ok this morning since testing, so maybe this is not a widespread issue and is more isolated to certain DAWs or opening files from NAS locations rather than internal SSDs. However, it would be nice to add a countdown feature, and have the progress bar window show always on top of other windows. This would be useful for both file opening and file saving.

**Comment by JeromeMartinez** [comment]
> 32 hour-long wav files

Wow... Ouch :).
Here with MD5 check, the issue is the storage speed, even with a SSD at 1 GB/s it takes ~30 seconds per file just for loading.
But saving should be fine (if no need to rewrite the full file e.g. adding chunks at the beginning)
Do you have MD5 check active? If so, is it slow also without this option?

> I will give the caveat that the progress bar has been performing ok this morning since testing, so maybe this is not a widespread issue and is more isolated to certain DAWs or opening files from NAS locations rather than internal SSDs. 

Can you provide a use case (OS, OS version, kind of NAS) when the tool does not respond?

**Comment by mwidzinski** [comment]
It is still slow with saving. Seems to take just as long to save with a generated MD5 as it does to open. I don't see a case where I personally would use BWF MetaEdit without checking the MD5, but it is faster is that is inactive. 

I will experiment and try to find a use case for the non-responsive behavior.

**Comment by mwidzinski** [comment]
I opened 60 items from a NAS on Windows 10 Enterprise 21H1 without generating the MD5. With the files still open, I opened preferences and selected "generate MD5". A pop up window appeared asking if I wanted to generate checksums for already-open files. I chose yes, then the system went into not responding.

**Comment by JeromeMartinez** [comment]
> It is still slow with saving. Seems to take just as long to save with a generated MD5 as it does to open.

I think I get a useless bottleneck here, reading the MD5 after saving, and it is more or less useless.

Just to be sure we are in sync about the use case, what are the checked MD5 options (Generate, Verify, Embed)?

> A pop up window appeared asking if I wanted to generate checksums for already-open files. I chose yes, then the system went into not responding.

It loads again all files and read files. Impossible to reduce the duration (limited by your storage speed) but it deserve a correct progress bar + estimation of duration.

**Comment by mwidzinski** [comment]
Yes, all three MD5 options are checked: Generate, Verify, Embed.

**Comment by EricJacobsTAA** [comment]
I just wanted to express our support for these performance improvements and
how they can improve productivity and increase BWFME usage.

We frequently only view or export existing metadata with BWFME (a kind of
“read-only mode”), without validation, and we’ve noticed some of these same
speed bumps as a user.

Our thanks to the BWFME team and power users.

Eric Jacobs
The Audio Archive

**Comment by dericed** [comment]
This is great. Thanks for your comment @EricJacobsTAA, user feedback means a lot in aiding developing and testing.

**Comment by MarcosSueiro** [comment]
Hello,

We are very excited about the new version of BWFME, and just wanted to thank you for supporting and for your hard work on this amazing (free!!!) tool.

Marcos

Marcos Sueiro Bal
Archive Manager
New York Public Radio
646 829 4063
160 Varick St
New York NY 10013
USA

**Comment by MarcosSueiro** [comment]
Hah! That’s entirely selfish 😉

Marcos Sueiro Bal
Archive Manager
New York Public Radio
646 829 4063
160 Varick St
New York NY 10013
USA

From: Dave Rice ***@***.***>
Sent: Wednesday, October 30, 2024 10:55 AM
To: Marcos Sueiro Bal ***@***.***>
Cc: MediaArea/BWFMetaEdit ***@***.***>; ***@***.***; Murray, Kate ***@***.***>
Subject: Re: BWFME

External email - Please exercise caution when opening attachments, clicking links, or sharing information.

________________________________
d’aw. And thank you for all you add to this project!


On Oct 30, 2024, at 10:49 AM, Marcos Sueiro Bal ***@***.******@***.***>> wrote:

Hello,

We are very excited about the new version of BWFME, and just wanted to thank you for supporting and for your hard work on this amazing (free!!!) tool.

Marcos

Marcos Sueiro Bal
Archive Manager
New York Public Radio
646 829 4063
160 Varick St
New York NY 10013
USA
