### ISSUE TITLE
Improve speed of opening/saving files

### ISSUE THREAD

**Issue by mwidzinski** [MediaArea/BWFMetaEdit#286]
I understand that this is a bigger ask, but it would be very helpful if BWF Metaedit could open/save large groups of files at a faster rate. I'm sometimes dealing with 32 wav files with around 28 GB of data at once and the opening/saving process slows the process down.

**Comment by JeromeMartinez** [comment]
Also without MD5 check?
Also saving with a small edit of a specific chunk e.g. removing 1 character?

**Comment by mwidzinski** [comment]
There is no speed problem if I open files without generating the MD5 checksum. Generating MD5s is a requirement for my work, though. Saving with a small edit (I removed 1 character from coding history in my test) was fast as well. I guess the slowdown comes with saving the generated MD5.

**Comment by MarcosSueiro** [comment]
Enhancement [255](https://github.com/MediaArea/BWFMetaEdit/issues/255) might help with this...

**Comment by JeromeMartinez** [comment]
> I guess the slowdown comes with saving the generated MD5.

Not saving (we append to the end of file), but generating the MD5 (need to read the whole file).
Not much to do there as we are mostly limited by the storage speed, but we'll check that we don't read too often the same content, maybe we compute before saving then compute again when parsing again the file, not sure.

**Comment by MarcosSueiro** [comment]
@JeromeMartinez does this fix #255 ?

**Comment by JeromeMartinez** [comment]
> @JeromeMartinez does this fix https://github.com/MediaArea/BWFMetaEdit/issues/255 ?

Partially, there is still some work to do for avoiding to compute MD5 in some corner cases.
