### ISSUE TITLE
Include FileCreate, FileModify dateTime in Technical output

### ISSUE THREAD

**Issue by MarcosSueiro** [MediaArea/BWFMetaEdit#287]
Hopefully this is not too complicated to implement... trying to have an alternative to exiftool for all our data 😁

**Comment by dericed** [comment]
seems reasonable and mediainfolib already has access to this data

**Comment by JeromeMartinez** [comment]
> seems reasonable and mediainfolib already has access to this data

but BWF MetaEdit doesn't use MediaInfoLib ;-).
In practice, it is just a `stat` (or equivalent on Windows) API call.

**Comment by JeromeMartinez** [comment]
@MarcosSueiro you mean that you need all in 1 output? Because if you can use 2 commands, MediaInfo has it ( ` -f` and/or a template) so need to duplicate works in BWF MetaEdit (not complicated but still more dev).

**Comment by MarcosSueiro** [comment]
> @MarcosSueiro you mean that you need all in 1 output? Because if you can use 2 commands, MediaInfo has it ( ` -f` and/or a template) so need to duplicate works in BWF MetaEdit (not complicated but still more dev).

Always looking for fewer commands... thanks @JeromeMartinez !
