### ISSUE TITLE
non 7-bit ASCII

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/BWFMetaEdit#29]
(Received by email)

(...) that used the open quotation (hex 93) and close quotation (hex 94) characters in their data and it didn't translate well at all!

**Comment by JeromeMartinez** [comment]
non 7-bit ASCII chars are problematic: actually, there is no indication in EBU tech 3285 about which locale is used.
on my Windows machine with code page 437 ("OEM-US"), when I test • (hex 95, because command line prompt transforms quotation marks to simple quotation hex 22) with command line, it is saved with hex 95 (which, I guess, would be translated differently on a non occidental machine...)
with the GUI, it is silently replaced by a question mark because it is not 7-bit ASCII.

I guess we can say it is a bug (especially because behavior is not same depending on the interface), and fixing it would not be easy (not technically, but debate about which locale to use in the file).

**Comment by dericed** [comment]
Isn't this closed via https://github.com/MediaArea/BWFMetaEdit/pull/34? Is there a part that is left?
