### ISSUE TITLE
Export > Core Document (one global CSV file)... Only exports last asset in list of files.

### ISSUE THREAD

**Issue by grammymix** [MediaArea/BWFMetaEdit#290]
Issue found in in Windows version specifically. With a hundred files in the window, BWF MetaEdit only exports information from the last item in the list!

**Comment by hocksteindw** [comment]
Experiencing this on Mac 14.5 as well, BWF MetaEdit ver 24.05

**Comment by dmarcuswalker** [comment]
Also experiencing this on Mac 13.6.7, BWF version 24.05

**Comment by hocksteindw** [comment]
Hi! The latest snapshot (20240928) still seems to have this issue.

**Comment by JeromeMartinez** [comment]
> Hi! The latest snapshot (20240928) still seems to have this issue.

Please test https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20240808-2/
(PR not yet merged, I'll review it soon and merge)

**Comment by hocksteindw** [comment]
Seems as though the 08/08 is not available via the link. The most recent snapshot in the directory is from 08/24.

**Comment by hocksteindw** [comment]
> > Hi! The latest snapshot (20240928) still seems to have this issue.
> 
> Please test https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20240808-2/ (PR not yet merged, I'll review it soon and merge)

Seems as though the 08/08 is not available via the link. The most recent snapshot in the directory is from 08/24.

**Comment by JeromeMartinez** [comment]
@hocksteindw please test https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20241002/

**Comment by hocksteindw** [comment]
> @hocksteindw please test https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20241002/

this seems to work. thank you!
