### ISSUE TITLE
GUI export core document (one global csv) function broken

### ISSUE THREAD

**Issue by bjpaulson61** [MediaArea/BWFMetaEdit#305]
The export core document (one global csv) is broken on all osx GUI versions since BWF MetaEdit 23.04.

 It only returns one line / item of data in CSV format when working on multiple files simultaneously.

 The export tech document (one global csv) function works as intended.

 Tested on OSX Ventura 13.7 and an older Monterrey install with the same results.

**Comment by g-maxime** [comment]
This should be fixed in the next release: https://github.com/MediaArea/BWFMetaEdit/pull/295

Please test a snapshot: https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20241026/BWFMetaEdit_GUI_24.05.20241026_Mac.dmg
