### ISSUE TITLE
Explanation text in GUI

### ISSUE THREAD

**Issue by privatezero** [MediaArea/BWFMetaEdit#32]
Using version 1.3.2 in Ubuntu I have noticed that the text explanations that are displayed when a user hovers their mouse over a BEXT element seem to have gotten a bit garbled.

The 'FADGI Recommendations'  text here: https://github.com/MediaArea/BWFMetaEdit/blob/master/Source/Resource/Documentation/bext.html#L23

Actually seems related to the guidelines for 'Originator' rather than 'Description.'

Similarly, the 'FADGI Examples' here:
https://github.com/MediaArea/BWFMetaEdit/blob/master/Source/Resource/Documentation/bext.html#L91

Are the examples given in the FADGI documentation for 'Originator,' not 'Originator Reference.'

**Comment by dericed** [comment]
Can you add a screen capture. I'm a bit confused since the linked html isn't the content of a tooltip.

**Comment by privatezero** [comment]
Sorry if I linked to the wrong location for the tool tips - no idea how qt puts things together so I just poked around until I found the offending text :-P

Here is a screenshot of the pop-up for 'Originator Reference'

![description_crop](https://user-images.githubusercontent.com/12941699/32236447-5eb530c2-be1f-11e7-98da-270c5c3570dc.png)

**Comment by privatezero** [comment]
Here is picture of 'Originator Reference' hover. Note 'FADGI Examples' actually correspond with those for 'Originator'

![orig_ref_crop](https://user-images.githubusercontent.com/12941699/32236795-73725b88-be20-11e7-8595-c23bcbb79aed.png)

**Comment by dericed** [comment]
Thx for clarifying. The tooltip text comes from here: https://github.com/MediaArea/BWFMetaEdit/blob/7c09856c7f5f389f9d2be05654e9fdc571e37a50/Source/Common/Common_About.cpp#L144.

**Comment by privatezero** [comment]
Ahhh thanks! I thought it might be doing something like Electron.js and be building a gui out of html!

**Comment by JeromeMartinez** [comment]
I tested on Ubuntu 16.04, first screenshot looks like the one for `Description`.
Is see from example that the issue is more on the "FADGI examples" part of `Originator` and `OriginatorReference` they are same (and they shouldn't, I guess), do I miss something?

**Comment by privatezero** [comment]
Now that @dericed pointed out the relevant section, it is also possible that I could take a stab at fixing this

**Comment by dericed** [comment]
B-)

**Comment by JeromeMartinez** [comment]
go, go!
Note that it looks like both HTML and tooltips are garbled, so both should be changed if it is the case.

**Comment by JeromeMartinez** [comment]
[Self-fixed](https://github.com/MediaArea/BWFMetaEdit/pull/33) :)
