### ISSUE TITLE
Missing Null Character on LIST-INFO

### ISSUE THREAD

**Issue by X-Raym** [MediaArea/BWFMetaEdit#42]
Hi,

I'm on Win 10 x64.

When I set a LIST-INFO field like IART (artist name), it appears truncated in windows explorer column display and file properties.

Though, the information seems valid for BWF MetaEdit or other software capable of reading LIST-INFO. But I noticed that adding `\x00` may solve the issue (I do that with a python script I made) (and also, size chunk have to be updated).

Here is a demo, using Riffpad to inspect chunks.:
![demo](https://i.imgur.com/BgtlNVu.gif)

Do you think it is a windows issue or a BWF MetaEdit one ?

Cheers !

**EDITED: 2018-06-15**: new screenshot

**Comment by X-Raym** [comment]
I confirm there is a missing bytes in BWF Meta Edit LIST- INFO Injection.

Here is a working file downloaded form there

![Original](https://monosnap.com/image/L0zRShbzhlaIalSTOUhi6QzKTAvbJH.png)

Here is the same values but passed through BWF Meta Edit

![BWF-Meta-Edit Truncated](https://monosnap.com/image/hHHJ3N9DLEdx7adwtnyqUpQHE7Qhq2.png)

As you can see there is missing bytes at the end.

(hex preview with https://hexed.it/)

**Comment by JeromeMartinez** [comment]
@X-Raym sorry about the delay, I check that next week.

**Comment by X-Raym** [comment]
Oh don't worry take your time ! I'll still add info I found somethings new.

So weird things is that this tools displayed differently in window but display same hex code for LIST - INFO - IART value...

Here are these files
https://www.dropbox.com/sh/mr24tcf7951og2n/AABcWfDs4yzImybzHwUp4gPGa?dl=0

Some maybe the error come from somehwere else. But there is definitely a problem for window.

**Comment by X-Raym** [comment]
@JeromeMartinez I renamed the issue, cause this is in fact not a windows related issue, but a BWF injection one.

**Comment by X-Raym** [comment]
I tried injecting an extra null characters right in the CLI command doesn't seems to work. I think only an internal fix can do it. :S

**Comment by X-Raym** [comment]
I tried to find where the Set WAV-INFO function was,

I think it is in this function but I'm not sure, https://github.com/MediaArea/BWFMetaEdit/blob/master/Source/Riff/Riff_Chunks_WAVE_INFO_xxxx.cpp#L98

And I don't know how to fix it.
Also, I don't know how to compile this code.

This is kindof hardcore lebel

@aaronbrownsound Do you need only BEXT or also LIST-INFO ?

**Comment by X-Raym** [comment]
@JeromeMartinez Thanks for your consideration, but I'm also sorry not to be able to debug and propose a fix (that is the interest of open source) ^^ All I was able to do is found the issue and back trace it. The rest is beyond my scope :S

**Comment by JeromeMartinez** [comment]
We missed a line in specs "Each chunk contains a ZSTR, or null-terminated text string", and Windows is weirdly handling the last char with files not adding this zero byte (it trashes it whatever is the content, i.e. even if it is not a zero, other tools usually just take the last byte if it is not zero).

Please test [this snapshot](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20180816/).

**Comment by X-Raym** [comment]
@JeromeMartinez Thanks for your work on this ! Glad you find the issue !

I tried with the windows GUI version with all fields and it works pretty fine. Windows display fields properly in every of my test.

Though, there is something a bit weird;
In some circumstances, adding extra characters to a field and then restore to the initial value create a FLLR chunk, rather than updating wav file as it was before.

![Demo](https://i.imgur.com/cmP7BSw.gif)

Is it something for the case where LIST-INFO chunks isn't the last chunk ?

**Comment by JeromeMartinez** [comment]
> In some circumstances, adding extra characters to a field and then restore to the initial value create a FLLR chunk, rather than updating wav file as it was before.

I don't remember exactly the reason, but current policy in BWF MetaEdit is to avoid to shrink a file, so a filler is added when you shrink it (file size is increased when you add 1 char, and for second edition of the file a shrink should be done without filling in order to revert to old size so BWF MetaEdit adds filling).

Such policy could be changed, but more code (and more tests), and it is not a bug, so not on free support.

**Comment by X-Raym** [comment]
@JeromeMartinez Understood ! That's ok, the file is working fine and its metadata also. I think it is good !

Will the version be bumped to v1.3.4 or stay at 1.3.3 ?

**Comment by JeromeMartinez** [comment]
> Will the version be bumped to v1.3.4 or stay at 1.3.3 ?

Currently this is in development snapshot only, so 1.3.3.20180816 style.
I'll release a new public version next week, tagged v1.3.4 as it is a major issue (invalid files are produced) so I don't wait for more development before doing a release.

**Comment by X-Raym** [comment]
@JeromeMartinez
Excellent !
Meanwhile I'll continue to experiment with it (especially the CLI version) and I'll report if I find anything.

**Comment by JeromeMartinez** [comment]
[v1.3.5 publicly released](https://mediaarea.net/BWFMetaEdit).

**Comment by X-Raym** [comment]
@JeromeMartinez Many thanks ! :)
