### ISSUE TITLE
Q/FR: Getting iXML from CLI

### ISSUE THREAD

**Issue by X-Raym** [MediaArea/BWFMetaEdit#51]
Hi,

Currently from CLI, I can only see a function to export iXML of a wav to a new file, but no way to just return this iXML as a string.

Do I miss anything ?
Could it be added for the future ? 😃 

Thx !

**Comment by JeromeMartinez** [comment]
I am a bit reluctant to add more options to the terminal output, especially XML ones, as the final output may be a bit incoherent e.g. core info then a XML output (so not XML valid at the end).
But maybe easy, I may check when I work on another feature.

**Comment by X-Raym** [comment]
@JerimeMartinez maybe it surely needs to be integrated as an extra dedicated parameter to avoid problem with parsing the returned string :P (so all other out functions are untouched).
Thx for your answer anyway !

**Comment by JeromeMartinez** [comment]
Sorry, this is what I wanted to mean, and there are still some potential conflicts in options (should we accept all option even if it breaks the XML, or reject incoherent options...), quick and dirty implementation is fast, handling impact on the coherency of the options is longer.

**Comment by MarcosSueiro** [comment]
@JeromeMartinez,and @g-maxime, is this merge-able with #196 ?
