### ISSUE TITLE
Bug: Impossible to open files with non ASCII characters in their names

### ISSUE THREAD

**Issue by X-Raym** [MediaArea/BWFMetaEdit#63]
Hi,

On Win 10x64, opening a file with a UTF-8 accent like

> Gravats débris pierre.wav

produced this error:

> 2019-06-18 17:17:39 E:\Bureau\Gravats dÃ©bris pierre.wav: File does not exist

I think file has to be escaped somewhere.

Meanwhile, I'll avoid any non-ASCII characters.

Thanks for your support !

**Comment by JeromeMartinez** [comment]
Sponsor were from the US and more on Mac, so this was definitely not well test with accents on Windows.
It is a bit messy on Windows, but not the most difficult.

**Comment by X-Raym** [comment]
@g-maxime Hi ! Any news on this ? :)

**Comment by dericed** [comment]
tested in the 20200401 release, I still get a "File does not exist" when there is unicode in the filename

**Comment by g-maxime** [comment]
New snapshot:
https://old.mediaarea.net/download/snapshots/binary/bwfmetaedit/20200402-6/

**Comment by JeromeMartinez** [comment]
Works for me on Windows.

**Comment by dericed** [comment]
I think the issue persists:

```
% ls -l Ƅ.wav 
-rw-r--r--@ 1 davidrice  staff  2700208 Apr  2 09:57 Ƅ.wav

% bwfmetaedit Ƅ.wav  
2020-04-06 13:45:52 Ƅ.wav: File does not exist

% bwfmetaedit -v
Usage: "bwfmetaedit [-Options...] FileName1 [Filename2...]"
"bwfmetaedit --Help" for displaying more information

% bwfmetaedit -V
Usage: "bwfmetaedit [-Options...] FileName1 [Filename2...]"
"bwfmetaedit --Help" for displaying more information

% bwfmetaedit --version
BWF MetaEdit 1.3.8.20200402
```

**Comment by JeromeMartinez** [comment]
Should be OK now on both Windows and Mac.
[latest snapshot](https://mediaarea.net/download/snapshots/binary/bwfmetaedit/20200407-7/).

**Comment by dericed** [comment]
I'm testing in "BWF MetaEdit 1.3.8.20200427" with the output of `ffmpeg -f lavfi -i sine -t 1 Ƅ.wav` and once again get a "File does not exist" error. Please re-open.

**Comment by g-maxime** [comment]
On macOS ?

```
bwfmetaedit --version
BWF MetaEdit 1.3.8.20200427
bwfmetaedit --out-core Ƅ.wav
FileName,Description,Originator,OriginatorReference,OriginationDate,OriginationTime,TimeReference (translated),TimeReference,BextVersion,UMID,LoudnessValue,LoudnessRange,MaxTruePeakLevel,MaxMomentaryLoudness,MaxShortTermLoudness,CodingHistory,IARL,IART,ICMS,ICMT,ICOP,ICRD,IENG,IGNR,IKEY,IMED,INAM,IPRD,ISBJ,ISFT,ISRC,ISRF,ITCH
Ƅ.wav,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Lavf58.29.100,,
```

**Comment by dericed** [comment]
same in cli, but no file found in gui
