### ISSUE TITLE
Bug: CLI version adds FLLR chunk and write chinks in wrong order

### ISSUE THREAD

**Issue by X-Raym** [MediaArea/BWFMetaEdit#64]
Hi,

I noticed a difference with injecting IART from the GUI version and IART from the CLI version (tested on windows 10 x64, v1.3.8 of BWFMetaEdit)

In the CLI version, LIST chunks isn't last chunk as it is supposed to be, and there is a mysterious FLLR chunk just after that.

The following image shows the difference: on top, BWFMetaEdit GUI version of IART = X-Raym injection, and same below but with CLI.

![img](https://monosnap.com/image/TexArEe6pciX76FdTL0TjFymPpLKxF.png)

It is surprising that the two versions output different results.

Sure thing is that CLI version is wrong cause metadata written this way are not recognized by windows explorer (but they works in less sensitive softwares)

![img](https://monosnap.com/image/p8f1qZ1gfY4Yvi7acEBdZq4sC2Gx4Q.png)

How come this difference ?

Thanks for your support !

**Comment by X-Raym** [comment]
@JeromeMartinez The problem seems not to be the FLLR chunk in particular but the fact that LIST-INFO is not last.

![img](https://monosnap.com/image/WuN1mMJ2eKoInPq6odnltJz2PQ8g6o.png)

Though, not having FLLR at all would be better :P especially if the GUI version can do it.

Thx for your support !

**Comment by X-Raym** [comment]
@JeromeMartinez Hi !

I'm bit a concerned about this issue, as it will happen on every CLI calls :S
Im affraid it invalidates the wav file on some players etc...

Can you take a look ?
It will be very appreciated.

Thx !

**Comment by JeromeMartinez** [comment]
Oops, looks like I forgot to handle this issue.
Please test [this snapshot](https://mediaarea.net/download/snapshots/binary/bwfmetaedit/20200201/), we fixed a couple of issues and maybe it includes your issue.

**Comment by X-Raym** [comment]
@JeromeMartinez Hi,
Just tested and it doesn't seems to have been fixed since.
Thanks for your support !

**Comment by X-Raym** [comment]
for extra precision, I used _BWFMetaEdit_CLI_1.3.8.20200201_Windows_x64.zip_.

**Comment by JeromeMartinez** [comment]
> I'm bit a concerned about this issue, as it will happen on every CLI calls :S

The file is valid from our point of view, looks like that Explorer has a lazy way to catch INFO-LIST.
We need to understand better what is accepted by Explorer.
In the meanwhile, using " --append" in the CLI is like "Place new or expanded BEXT and
INFO-LIST chunks at the end of file" option in the the GUI, and is a workaround for that (it forces the INFO-LIST at the end).

**Comment by X-Raym** [comment]
@JeromeMartinez Thanks for your expertise,
So this `append` solution seems nice, and cleaner -has there is no useless FLLR data.

Has this been implemented ? Cause I just tried and didn't see any difference :

```bash
bwfmetaedit "E:\Bureau\ghgh\a.wav" --INAM="Test" --Description="X-Raym" --IART="X-Raym" --append
```

![img](https://i.imgur.com/CgFnAly.gif)

Thanks for your support !

**Comment by g-maxime** [comment]
@X-Raym  Is INFO chunk already presents ?

Working for me: https://gist.github.com/g-maxime/25b6e92cdf71d6c0ad9376b8575ca0d0

**Comment by X-Raym** [comment]
@g-maxime yes indeed that was it !

Ok thanks I will continue to experiment from there, but this solve my issue. I'll always use append then. I close this for now and reopen if any issue.

Thanks for your support !
