### ISSUE TITLE
TimeReference GUI input integer type too small for files >48000Hz

### ISSUE THREAD

**Issue by RyLo2797** [MediaArea/BWFMetaEdit#70]
The TimeReference input value in the GUI seems to be limited to a 32 bit unsigned integer. If the WAV file has a sample rate greater than 48KHz, you can hit the limit. 

At 96000Hz, if you input a timecode in the TimeReference (translated) box that's greater than 12:25:39.242, the timecode will change to that value and the TimeReference value will change to 4294967295. Similarly, you can't input a TimeReference value greater than 4294967295.

This was tested in the 64 bit Windows version of the GUI. The 64 bit Windows version of the CLI doesn't have the same issue.

**Comment by g-maxime** [comment]
Fixed by #82
