### ISSUE TITLE
logo :)

### ISSUE THREAD

**Issue by dericed** [MediaArea/BWFMetaEdit#76]
See https://github.com/MediaArea/BWFMetaEdit/issues/73#issuecomment-572286690. Currently BWF MetaEdit re-uses the FADGI logo and in some cases causes identify confusion.

**Comment by ablwr** [comment]
What about something very basic, like this, that can be applied to all of the MetaEdits, and tie them to MediaArea's logo?

![Screenshot from 2020-02-01 11-13-58](https://user-images.githubusercontent.com/3260492/73595217-f95b5a00-44e3-11ea-9f7a-5b34c301c8cf.png)

**Comment by dmarcuswalker** [comment]
> What about something very basic, like this, that can be applied to all of the MetaEdits, and tie them to MediaArea's logo?
> 
> ![Screenshot from 2020-02-01 11-13-58](https://user-images.githubusercontent.com/3260492/73595217-f95b5a00-44e3-11ea-9f7a-5b34c301c8cf.png)

I like this proposed version!

**Comment by dericed** [comment]
@ablwr could you make a PR with the proposed icon into https://github.com/MediaArea/BWFMetaEdit/tree/master/Source/Resource/Image/FADGI

**Comment by JeromeMartinez** [comment]
@ablwr the SVG for each of the 3 projects on their respective repo please.

**Comment by ablwr** [comment]
Sure thing!

What formats do you need?

Dave's path has icns, ico, and two PNG sizes. Should I replace all of those, or do you want to update/change/move? For SVG, where should I put it?

**Comment by JeromeMartinez** [comment]
@ablwr the path should be /Source/Resource/Image/BWFMetaEdit.svg (FADGI subdir is for FADGI, here we move for FADGI logo for both FADGI link and icon to only FADGI link, so we need a new place for the logo itself), similar to the [MediaInfo one](https://github.com/MediaArea/MediaInfo/blob/master/Source/Resource/Image/MediaInfo.svg).

Then @g-maxime will check and create the currently needed icon formats and sizes (platform rules for icons change over time, [sometimes with a long list of requested images](https://github.com/MediaArea/MediaInfo/tree/master/Source/Resource/Image/Assets).

**Comment by ablwr** [comment]
OK great!! Thanks @JeromeMartinez!

**Comment by ablwr** [comment]
(partially)

**Comment by JeromeMartinez** [comment]
Closed with https://github.com/MediaArea/BWFMetaEdit/pull/85 then https://github.com/MediaArea/BWFMetaEdit/pull/88.
@ablwr don't forget the other projects please, so we have all of them with new logos (in dev snapshots).

**Comment by ablwr** [comment]
Yep, coming right up!!

This doesn't look great in a darkmode context, but it would be interested to see on a Mac. I feel like Linux users like myself are used to ill-fitting logos. Here's how it fits in next to the also-very-dark Inkscape logo.

![Screenshot from 2020-04-08 12-11-16](https://user-images.githubusercontent.com/3260492/78807396-00925e80-7992-11ea-9c10-248c1ca6a21d.png)

A bit mysterious.

**Comment by JeromeMartinez** [comment]
Looks slightly better on macOS (background seems less dark):
![image](https://user-images.githubusercontent.com/1641638/78808903-626cbb80-79c6-11ea-9505-99df1ab34b68.png)
And the title bar:
![image](https://user-images.githubusercontent.com/1641638/78808994-89c38880-79c6-11ea-857e-232b529fdb90.png)
But when focus is away, it is not so good:
![image](https://user-images.githubusercontent.com/1641638/78809051-9f38b280-79c6-11ea-883c-0cc2cc17f09c.png)

The way e.g. Android manages that is to mandate a background circle, but not sure I would like to go in this direction when not mandatory, maybe in the future there will be more options for dark mode e.g. the possibility of an alternate logo in dark mode and in that case we show the waves and name in white.

**Comment by ablwr** [comment]
OK great. Yeah I agree, better to have these in place and could potentially be improved later.
