### ISSUE TITLE
Drag-and-drop CSV to GUI issues on Mac 10.14

### ISSUE THREAD

**Issue by dmarcuswalker** [MediaArea/BWFMetaEdit#83]
On BWF MetaEdit 1.3.8, dragging and dropping the CORE document into the GUI does not pull up any files. Importing the CSV "sometimes" works but other times produces the error "File does not exist" for all items in the document. This issue has been observed on multiple workstations. The workaround has been to drag the CORE document into the GUI only after all of the files have been loaded in.

**Comment by dericed** [comment]
closed by https://github.com/MediaArea/BWFMetaEdit/pull/84?

**Comment by JeromeMartinez** [comment]
Available in [snapshots](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/).
