### ISSUE TITLE
Cannot overwrite longer CodingHistory

### ISSUE THREAD

**Issue by MarcosSueiro** [MediaArea/BWFMetaEdit#90]
Both CLI and GUI are unable to delete old, longer free-text CodingHistory. 

In other words, if I have a long free text coding history such as 

“LONG CODING HISTORY”

and I want to update it to 

“Short history”,

once I save the changes, it becomes

“Short historyHISTORY”

I.e., I can overwrite characters, but the old characters “stick out” afterwards.

Marcos

**Comment by g-maxime** [comment]
Please provide more information (BWFMetaEdit version and OS).

You can also try latest snapshots [CLI](https://old.mediaarea.net/download/snapshots/binary/bwfmetaedit/20200415-3/), [GUI](https://old.mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20200415-3/)

**Comment by MarcosSueiro** [comment]
BWF MetaEdit 1.3.1
Windows 10 Enterprise

**Comment by retokromer** [comment]
BWF MetaEdit 1.3.1 is six years (plus two days) old.

**Comment by MarcosSueiro** [comment]
Apologies! All good.

**Comment by JeromeMartinez** [comment]
Does it mean that it is OK with one of the latest versions? Either the release one 1.3.8 or the dev snapshot.

**Comment by MarcosSueiro** [comment]
Hi Jerome, 

Yes, it appears to work properly on 1.3.8.

Thanks
